name: Node.js CI.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: '18.x'

      - name: Debug current directory
        run: |
          echo "Current Directory: $(pwd)"
          Get-ChildItem -Recurse  # List files to ensure repository is checked out

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}  # Ensure the working directory is correct
          npm install --verbose=true --customCommand=install --customRegistry=useNpmrc --customFeed="" --customEndpoint="" --publishRegistry=useExternalRegistry --publishFeed="" --publishPackageMetadata=true --publishEndpoint=""

      - name: Run the application
        run: |
          cd ${{ github.workspace }}  # Ensure the working directory is correct
          node index.js
